### ISSUE TITLE
Error ... or enable "Allow Route Conflicts" option.	

### ISSUE THREAD

**Issue by mgheorghe** [vikumarks/msfthero#6]
CPS: Error	Test Controller	Network Network1 has different specific subnets configured - 13.0.0.0, 14.0.0.0, 15.0.0.0, 16.0.0.0. If you want them to be on different specific subnets, either configure a valid gateway address for at least 3 of these specific subnets or enable "Allow Route Conflicts" option.

**Comment by albertovillarreal-keys** [comment]
This is already included in the script, lets talk about this one.

look at:
hero_helper.py line 34
 'allow_routes': {
            'json': {'allowRouteConflicts': True},
            'url': "/ixload/preferences"
        },

line 776
response = self._patch_test_setting(self.url_patch_dict, 'allow_routes')

**Comment by mgheorghe** [comment]
script is fine but since setting is not saved in config if config is moved on a different user , that user will have to set his env settings
